// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjUXiIuKHnKY7D4gGVbm6e9GsIlaPOvI',
    appId: '1:382803214113:web:452431c12d2dc707de4860',
    messagingSenderId: '382803214113',
    projectId: 'chat-room-7c0a4',
    authDomain: 'chat-room-7c0a4.firebaseapp.com',
    storageBucket: 'chat-room-7c0a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxIfaMCXqgDbKJASmr0y7UbAUPdztX2U',
    appId: '1:382803214113:android:f57c7a1c48c0d703de4860',
    messagingSenderId: '382803214113',
    projectId: 'chat-room-7c0a4',
    storageBucket: 'chat-room-7c0a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nhraNb2TmWw-89t9ioodv5B9VYmoyOk',
    appId: '1:382803214113:ios:35588d2916917921de4860',
    messagingSenderId: '382803214113',
    projectId: 'chat-room-7c0a4',
    storageBucket: 'chat-room-7c0a4.appspot.com',
    iosClientId: '382803214113-h4ohgk3rk8se96bboh9l9krpqomn7bok.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nhraNb2TmWw-89t9ioodv5B9VYmoyOk',
    appId: '1:382803214113:ios:35588d2916917921de4860',
    messagingSenderId: '382803214113',
    projectId: 'chat-room-7c0a4',
    storageBucket: 'chat-room-7c0a4.appspot.com',
    iosClientId: '382803214113-h4ohgk3rk8se96bboh9l9krpqomn7bok.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
