const Map<String, String> ar = {
  //butten
  "Sign_In": "تسجيل دخول",
  "Register": "انشاء حساب",
  "send": "ارسال",
  "Save": "حفط",
  "add_room": "اضافة غرفة",
  "New_Room": "انشاء غرفة",
  "Out_the_room": "الخروج من الغرفة",
  "cancel": "الغاء",
  //Text
  "home": "الصفحة الرئيسية",
  "by_easzy_codey": "by easzy codey",
  "Darck_Mood": "الوضع المضلم",
  "my_account": "حسابي",
  "Email": "الايميل : ",
  "phone_Namber": "رقم الهاتف : ",
  "Password": "رمز الامان : ",
  "stening": 'اعدادات',
  "Language": "اللغة",
  "conect_us": "اتصل بنا",
  "Sign_out": "تسجيل الحروج",
  "Loading": "جاري التحميل",
  "Something went wrong": "Something went wrong",
  "Add_Mesh": "انشاء مهمة",
  "members": "الاعضاء",
  "edit_room_name": "تعديل اسم الغرفة",

  // text inpot
  "Enter_Your_Email": "ادخل البريد الالكتروني",
  "Enter_the_Email_correctlyy": "ادخال الايميل بشكل صحيح",
  "Enter Your Password": "ادخل كلمة السر",
  "Enter_at_least_6_character": "ادخل على اقل 6 احرف",
  "password_does_not_match": "كلمة السر غير متطابقة",
  "Confer_Your_password": "تاكيد كلمة السر",
  "Create a new account ?": "انشاء حساب جديد ?",
  "write_you_message": "اكتب رسالتك ...",
  "Input Your Name App": "ادخل اسم الاتطبيق",
  "UIL Web": "رابط موقع الالكتروني",
  "Input Your UIL web": "ادخل رابط موقع الالكتروني",
  "Name": "الاسم",
  "Input_Your_Name": "ادخل الاسمك",
  "naw_name": "الاسم الجديد",
};
