const Map<String, String> en = {
  //butten
  "Sign_In": "Sign In",
  "Register": "Register",
  "send": "Send",
  "Save": "Save",
  "add_room": "Add room",
  "New_Room": "New room",
  "Out_the_room": "Out the room",
  "cancel": "Cancel",
  //Text
  "home": "Home",
  "by_easzy_codey": "by easzy codey",
  "Darck_Mood": "Darck Mood",
  "my_account": "my Account",
  "Email": "Email : ",
  "phone_Namber": "Phone Namber : ",
  "Password": "Password : ",
  "stening": 'Stening',
  "Language": "Language",
  "conect_us": "Conect Us",
  "Sign_out": "Sign Out",
  "Loading": "Loading...",
  "Something went wrong": "Something went wrong",
  "Add_Mesh": "New task",
  "members": "Members",
  "edit_room_name": "Edit room name",

  // text inpot
  "Enter_Your_Email": "Enter Your Email",
  "Enter_the_Email_correctlyy": "Enter the Email correctlyy",
  "Enter Your Password": "Enter Your Password",
  "Enter_at_least_6_character": "Enter at least 6 character",
  "password_does_not_match": "password_does_not_match",
  "Confer_Your_password": "Confer_Your_password",
  "Create a new account ?": "Create a new account ?",
  "write_you_message": "Write you message...",
  "Input Your Name App": "Input Your Name App",
  "UIL Web": "UIL Web",
  "Input Your UIL web": "Input Your UIL web",
  "Name": "Name",
  "Input_Your_Name": "Input Your Name",
  "naw_name": "Naw name",
};
